name: Build Electron App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build Electron app (Windows)
      if: matrix.os == 'windows-latest'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx electron-builder --win --x64

    - name: Build Electron app (macOS)
      if: matrix.os == 'macos-latest'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx electron-builder --mac --x64 --arm64

    - name: Upload Windows EXE
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v7
      with:
        name: LocalPitchPlayer-Windows-exe
        path: dist/*.exe

    - name: Upload Windows APPX
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v7
      with:
        name: LocalPitchPlayer-Windows-appx
        path: dist/*.appx

    - name: Upload macOS DMG
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v7
      with:
        name: LocalPitchPlayer-macOS-dmg
        path: dist/*.dmg

    - name: Upload macOS ZIP
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v7
      with:
        name: LocalPitchPlayer-macOS-zip
        path: dist/*.zip
